version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        RUBY_VERSION: 2.5.1
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - vendor:/vendor
      - .:/time_tracker:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env

volumes:
  dbdata:
  vendor:
