FROM ruby:2.5.1

RUN apt-get update -qq && apt-get install -y build-essential nodejs default-libmysqlclient-dev

# install yarn
RUN apt-get update && apt-get install -y curl apt-transport-https wget && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
    apt-get install nodejs

RUN mkdir /time_tracker
WORKDIR /time_tracker

ADD Gemfile /time_tracker/Gemfile
ADD Gemfile.lock /time_tracker/Gemfile.lock

RUN bundle config build.nokogiri --use-system-libraries \
	    bundle update sinatra

# install entrykit
ENV ENTRYKIT_VERSION 0.4.0
RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink

COPY docker /docker

ENTRYPOINT ["prehook", "/docker/prehook", "--"]
