FROM ruby:2.5

RUN apt-get update -qq && apt-get install -y build-essential nodejs default-libmysqlclient-dev

RUN mkdir /time_tracker
WORKDIR /time_tracker

ADD Gemfile /time_tracker/Gemfile
ADD Gemfile.lock /time_tracker/Gemfile.lock

RUN bundle install

ADD . /time_tracker
