#!/usr/bin/env bash

if [ -e Gemfile ]; then
  bundle check || bundle install
fi

if [ -e package.json ]; then
  (yarn check --integrity && yarn check --verify-tree) || yarn install
fi

 if [ -e tmp/pids/server.pid ]; then
  rm tmp/pids/server.pid
fi
