default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: db

development:
  <<: *default
  database: time_tracker_development

test:
  <<: *default
  database: time_tracker_test

production:
  <<: *default
  database: time_tracker_production
  username: time_tracker
  password: <%= ENV['TIME_TRACKER_DATABASE_PASSWORD'] %>
