default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  database: time_tracker_development
  username: root
  password:
  host: db

test:
  <<: *default
  adapter: mysql2
  database: time_tracker_test
  username: root
  password:
  host: db

production:
  <<: *default
  adapter: posgresql
  url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
