# https://dependabot.com/docs/config-file/
# version: 1

# update_configs:
#   - package_manager: "ruby:bundler"
#     directory: "/"
#     update_schedule: "weekly"
#    default_reviewers:
#       - kojoma
#    ignored_updates:
#       - match:
#           dependency_name: "rails"
